apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: locations-kafka-consumer
  name: locations-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locations-kafka-consumer
  template:
    metadata:
      labels:
        app: locations-kafka-consumer
    spec:
      hostname: locations-kafka-consumer
      containers:
      - image: akhidockhub/locations_kafka_consumer
        imagePullPolicy: Always
        name: locations-kafka-consumer
        env:
         - name: PYTHONUNBUFFERED
           value: "1"
         - name: DB_USERNAME
           valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
         - name: DB_PASSWORD
           valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
         - name: DB_NAME
           valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
         - name: DB_HOST
           valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
         - name: DB_PORT
           valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
